version: '2.19.1'

services:
  student-database:
    image: 'postgres:16.3-alpine3.19'
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: school
    ports:
      - '5432:5432'
    volumes:
      - './postgres-data:/var/lib/postgresql'
